### ISSUE TITLE
Summarize_Params doesn't like when you don't run all fxns

### ISSUE THREAD

**Issue by domjacri** [neurogenetics/SAHA#11]
For instance in an ann object that self sim was not run:
>> ann = Summarize_Params(ann) <br>
>Error in data.frame(Analysis = "Self_Sim", Input = "Query", Function = "Create_SelfSimilarity_Viz",  : <br>
>arguments imply differing number of rows: 1, 0

Fix so that it checks what is done before writing df to ann@params$summary

**Comment by richardmustaklem** [comment]
Pushed changes, please check the latest version for errors

**Comment by domjacri** [comment]
Passed several test cases:

- Only AvgExp -> Markerfree
- Only Create -> no analysis
- Only Markers -> Iniatilize 

Great job @richardmustaklem, I'll close it
