### ISSUE TITLE
'SAHA' requires R >= 4.3

### ISSUE THREAD

**Issue by junghpark** [neurogenetics/SAHA#17]
**ERROR: this R is version 4.2.1, package 'SAHA' requires R >= 4.3**

Can I use SAHA with an older version of R? Thanks!

**Comment by richardmustaklem** [comment]
I have not tried using SAHA with older versions of R. 

Either of these options should work though:

 1. Upgrade to a newer version of R (eventually you will need to do this anyways for future package releases) 

 2. Manually change the SAHA R Dependency in the Description File.

Option 2 is not recommended however changing the dependency isn't too difficult. If you decide to do this option, go to {path/of/SAHA/SAHA-main/DESCRIPTION}. Inside the DESCRIPTION file is where you can change the R dependency. 

Let me know if you have any other questions!
